name: "BATS Tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  bats-tests:
    name: End to End BATS Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Get bats derivation
        id: bats-derivation
        run: |
          nix build .#bats --dry-run --json | jq -r '.[].outputs.out' > nix-checks-paths.txt
          echo "Checks to wait for:"
          cat nix-checks-paths.txt
      - name: Wait for .#bats in Cachix
        uses: ./.github/actions/wait-for-cachix-paths
        with:
          paths-file: ./nix-checks-paths.txt
          cache-name: lana-bank-ci
          max-attempts: 300
          retry-delay: 10

      - uses: cachix/cachix-action@v15
        with:
          name: lana-bank-ci
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - name: Run BATS tests
        run: nix run .#bats
          
      - name: Rename bats log
        if: always()
        run: mv .e2e-logs e2e-logs || true
        
      - name: Upload bats log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BATS Logs
          path: |
            e2e-logs
            *.e2e-logs 
