name: "BATS Tests"
on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  bats-tests:
    name: End to End BATS Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Wait for .#bats in Cachix
        run: |
          nix build .#bats --dry-run --json | jq -r '.[].outputs.out' > nix-checks-paths.txt
          echo "Checks to wait for:"
          cat nix-checks-paths.txt
          nix run ./ci#wait-cachix-paths -- \
            -p ./nix-checks-paths.txt \
            -c galoymoney \
            -a 300 \
            -d 10
      - uses: cachix/cachix-action@v15
        with:
          name: galoymoney
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Run BATS tests
        run: nix run .#bats
          
      - name: Rename bats log
        if: always()
        run: mv .e2e-logs e2e-logs || true
        
      - name: Upload bats log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BATS Logs
          path: |
            e2e-logs
            *.e2e-logs
