name: "Nextest Tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  nextest-tests:
    name: Nextest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Wait for .#nextest in Cachix
        id: nextest-derivation
        run: |
          nix build .#nextest --dry-run --json | jq -r '.[].outputs.out' > nix-checks-paths.txt
          echo "Checks to wait for:"
          cat nix-checks-paths.txt
          nix run ./ci#wait-cachix-paths -- \
            -p ./nix-checks-paths.txt \
            -c galoymoney \
            -a 300 \
            -d 10

      - uses: cachix/cachix-action@v15
        with:
          name: galoymoney
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - name: Run Nextest tests
        run: nix run .#nextest
        env:
          SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
          SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
